/**
 * generator.js — Rising Edge IBIS-Studio
 * Guided IBIS model creation and Monaco editor integration.
 *
 * Depends on: Monaco Editor (CDN), IBISParser
 * Exports global: Generator
 */

const Generator = (function () {
  'use strict';

  let _editor = null;
  let _monacoReady = false;

  /* ─── Default form values ───────────────────────────────────────── */
  const DEFAULTS = {
    ibisVer: '7.0',
    fileName: 'new_model.ibs',
    fileRev: '1.0',
    date: new Date().toISOString().split('T')[0],
    source: 'IBIS-Studio — Rising Edge',
    notes: '',
    manufacturer: '',
    component: 'MY_COMPONENT',
    rPkg: '0.10m',
    lPkg: '2.5n',
    cPkg: '0.5p',
    modelName: 'MY_MODEL',
    modelType: 'Output',
    voltageTyp: '3.3',
    voltageMin: '3.0',
    voltageMax: '3.6',
    tempTyp: '25',
    tempMin: '0',
    tempMax: '85',
    cCompTyp: '2.0p',
    cCompMin: '1.5p',
    cCompMax: '2.5p',
    dvdtRTyp: '1.2',
    dvdtRMin: '0.9',
    dvdtRMax: '1.5',
    dvdtFTyp: '1.2',
    dvdtFMin: '0.9',
    dvdtFMax: '1.5',
    rload: '50',
  };

  /* ─── Monaco loader ─────────────────────────────────────────────── */
  function ensureMonaco(callback) {
    if (_monacoReady && _editor) {
      callback();
      return;
    }

    const container = document.getElementById('monaco-container');
    if (!container) return;

    // Wait for Monaco require to be available
    if (typeof require === 'undefined') {
      // Monaco loader script not ready yet
      setTimeout(() => ensureMonaco(callback), 200);
      return;
    }

    require.config({ paths: { vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs' } });
    require(['vs/editor/editor.main'], () => {
      // Register IBIS language
      monaco.languages.register({ id: 'ibis' });
      monaco.languages.setMonarchTokensProvider('ibis', {
        tokenizer: {
          root: [
            [/\|.*$/, 'comment'],
            [/\[[^\]]+\]/, 'keyword'],
            [/[+-]?\d*\.?\d+([eE][+-]?\d+)?[fpnumkMG]?/, 'number'],
            [/\b(NA|na|N\/A)\b/, 'invalid'],
          ],
        },
      });

      const dark = document.documentElement.getAttribute('data-theme') !== 'light';
      _editor = monaco.editor.create(container, {
        language: 'ibis',
        theme: dark ? 'vs-dark' : 'vs',
        fontSize: 12,
        fontFamily: "'JetBrains Mono', 'Fira Code', 'Courier New', monospace",
        minimap: { enabled: false },
        scrollBeyondLastLine: false,
        wordWrap: 'on',
        automaticLayout: true,
        tabSize: 2,
      });

      _editor.onDidChangeModelContent(() => {
        updatePreviewFromEditor();
      });

      _monacoReady = true;
      callback();
    });
  }

  /* ─── IBIS text generator ───────────────────────────────────────── */
  function buildIBISText(vals) {
    const v = { ...DEFAULTS, ...vals };
    const now = v.date;

    // Build a realistic I(V) table for output model
    const vdd = parseFloat(v.voltageTyp) || 3.3;
    const pullupTable = generateIVTable('pullup', vdd);
    const pulldownTable = generateIVTable('pulldown', vdd);
    const pwrClampTable = generateIVTable('pwr_clamp', vdd);
    const gndClampTable = generateIVTable('gnd_clamp', vdd);

    const isOutput = /output|io|3-state/i.test(v.modelType);
    const isInput = /input/i.test(v.modelType);

    let text = `[IBIS Ver]      ${v.ibisVer}
[File Name]     ${v.fileName}
[File Rev]      ${v.fileRev}
[Date]          ${now}
[Source]        ${v.source}
| Generated by IBIS-Studio — Rising Edge
${v.notes ? `[Notes]         ${v.notes}\n` : ''}

[Component]     ${v.component}
[Manufacturer]  ${v.manufacturer || 'Unknown'}

[Package]
| variable      typ         min         max
R_pkg           ${_padVal(v.rPkg)}  ${_padVal(v.rPkg)}  ${_padVal(v.rPkg)}
L_pkg           ${_padVal(v.lPkg)}  ${_padVal(v.lPkg)}  ${_padVal(v.lPkg)}
C_pkg           ${_padVal(v.cPkg)}  ${_padVal(v.cPkg)}  ${_padVal(v.cPkg)}

[Pin]  signal_name     model_name
1      ${_padStr(v.component + '_IO', 16)} ${v.modelName}

[Model]         ${v.modelName}
Model_type      ${v.modelType}
`;

    if (isInput || v.modelType === 'I/O') {
      text += `Vinl            ${(vdd * 0.3).toFixed(2)}
Vinh            ${(vdd * 0.7).toFixed(2)}
`;
    }

    text += `Vmeas           ${(vdd * 0.5).toFixed(2)}
Cref            0
Rref            50
Vref            0

[Voltage Range]   ${v.voltageTyp}         ${v.voltageMin}       ${v.voltageMax}
[Temperature Range] ${v.tempTyp}          ${v.tempMin}          ${v.tempMax}
[C_comp]          ${v.cCompTyp}           ${v.cCompMin}         ${v.cCompMax}

`;

    if (isOutput || v.modelType === 'I/O' || v.modelType === '3-state') {
      text += `[Pullup]\n| voltage     I(typ)      I(min)      I(max)\n`;
      text += pullupTable;
      text += `\n[Pulldown]\n| voltage     I(typ)      I(min)      I(max)\n`;
      text += pulldownTable;
    }

    text += `\n[Power Clamp]\n| voltage     I(typ)      I(min)      I(max)\n`;
    text += pwrClampTable;
    text += `\n[GND Clamp]\n| voltage     I(typ)      I(min)      I(max)\n`;
    text += gndClampTable;

    if (isOutput || v.modelType === 'I/O') {
      text += `
[Ramp]
| variable   typ          min          max
dV/dt_r      ${v.dvdtRTyp}/1n       ${v.dvdtRMin}/1n       ${v.dvdtRMax}/1n
dV/dt_f      ${v.dvdtFTyp}/1n       ${v.dvdtFMin}/1n       ${v.dvdtFMax}/1n
R_load       ${v.rload}

[Rising Waveform]
R_fixture     ${v.rload}
V_fixture     ${vdd}
| time        V(typ)      V(min)      V(max)
`;
      text += generateWaveform('rising', vdd, parseFloat(v.dvdtRTyp));

      text += `
[Falling Waveform]
R_fixture     ${v.rload}
V_fixture     0
| time        V(typ)      V(min)      V(max)
`;
      text += generateWaveform('falling', vdd, parseFloat(v.dvdtFTyp));
    }

    text += `\n[End]\n`;
    return text;
  }

  function generateIVTable(type, vdd) {
    const rows = [];
    if (type === 'pullup') {
      // I vs V relative to Vdd for pullup
      for (let vRel = -vdd; vRel <= 0.1; vRel += vdd / 6) {
        const v = Math.round(vRel * 1000) / 1000;
        const i = _pullupI(v, vdd);
        rows.push(`${_padV(v)}    ${_padI(i)}    ${_padI(i * 0.85)}   ${_padI(i * 1.15)}`);
      }
    } else if (type === 'pulldown') {
      for (let vAbs = 0; vAbs <= vdd * 1.2; vAbs += vdd / 6) {
        const v = Math.round(vAbs * 1000) / 1000;
        const i = _pulldownI(v, vdd);
        rows.push(`${_padV(v)}    ${_padI(i)}    ${_padI(i * 0.85)}   ${_padI(i * 1.15)}`);
      }
    } else if (type === 'pwr_clamp') {
      for (let vRel = -vdd * 1.5; vRel <= 0.1; vRel += vdd / 4) {
        const v = Math.round(vRel * 1000) / 1000;
        const i = v < -0.7 ? (v + 0.7) * 0.1 : 0;
        rows.push(`${_padV(v)}    ${_padI(i)}    ${_padI(i * 0.9)}   ${_padI(i * 1.1)}`);
      }
    } else {
      // gnd_clamp
      for (let v = -vdd * 1.5; v <= 0.1; v += vdd / 4) {
        const vr = Math.round(v * 1000) / 1000;
        const i = vr < -0.7 ? (vr + 0.7) * 0.1 : 0;
        rows.push(`${_padV(vr)}   ${_padI(i)}    ${_padI(i * 0.9)}   ${_padI(i * 1.1)}`);
      }
    }
    return rows.join('\n') + '\n';
  }

  function _pullupI(v, vdd) {
    // Simple PMOS model: Ids ~ (Vgs-Vtp)^2 in saturation
    const Vtp = -0.8,
      Ron = 15;
    const Vgs = v; // relative to Vdd
    if (Vgs > Vtp) return 0;
    return Math.max((Vgs - Vtp) ** 2 / (2 * Ron), (Vgs - Vtp) / Ron);
  }

  function _pulldownI(v, vdd) {
    const Vtn = 0.7,
      Ron = 15;
    if (v < Vtn) return 0;
    const Vds = v;
    const Vgs = vdd;
    // Triode if Vds < Vgs - Vtn
    if (Vds < Vgs - Vtn) {
      return (2 * (Vgs - Vtn) * Vds - Vds ** 2) / (2 * Ron);
    }
    return (Vgs - Vtn) ** 2 / (2 * Ron);
  }

  function generateWaveform(type, vdd, slew) {
    const rows = [];
    const tRise = vdd / (slew * 1e9); // seconds
    const tTotal = tRise * 4;
    const steps = 12;
    for (let i = 0; i <= steps; i++) {
      const t = (i / steps) * tTotal;
      let v;
      if (type === 'rising') {
        v = Math.min(vdd, Math.max(0, slew * 1e9 * Math.max(0, t - tRise * 0.5)));
      } else {
        v = Math.max(0, vdd - slew * 1e9 * Math.max(0, t - tRise * 0.5));
      }
      rows.push(
        `${_padV(t)}    ${_padV(v.toFixed(4))}    ${_padV((v * 0.92).toFixed(4))}    ${_padV((v * 1.08 > vdd ? vdd : v * 1.08).toFixed(4))}`
      );
    }
    return rows.join('\n') + '\n';
  }

  function _padV(v) {
    return String(v).padEnd(12);
  }
  function _padI(i) {
    return i.toExponential(3).padEnd(12);
  }
  function _padVal(s) {
    return String(s).padEnd(12);
  }
  function _padStr(s, n) {
    return String(s).padEnd(n);
  }

  /* ─── Form → text → editor ─────────────────────────────────────── */
  function readFormValues() {
    const vals = {};
    document.querySelectorAll('.gen-form [data-field]').forEach(el => {
      vals[el.dataset.field] = el.value || el.dataset.default || '';
    });
    return vals;
  }

  function updateEditorFromForm() {
    const vals = readFormValues();
    const text = buildIBISText(vals);
    if (_editor) {
      _editor.setValue(text);
    }
  }

  function updatePreviewFromEditor() {
    if (!_editor) return;
    const text = _editor.getValue();
    const previewEl = document.getElementById('ibis-preview');
    if (previewEl) {
      previewEl.textContent = text.slice(0, 2000) + (text.length > 2000 ? '\n...' : '');
    }
  }

  /* ─── Export current model ──────────────────────────────────────── */
  function exportCurrent() {
    const text = _editor ? _editor.getValue() : buildIBISText(readFormValues());
    const fileName = readFormValues().fileName || 'model.ibs';
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 5000);
    if (typeof IBISApp !== 'undefined') IBISApp.showToast('IBIS file downloaded', 'success');
  }

  /* ─── Load model into editor for editing ────────────────────────── */
  function loadForEditing(parsed) {
    ensureMonaco(() => {
      if (_editor && parsed.raw) {
        _editor.setValue(parsed.raw);
      }
    });
  }

  /* ─── Public API ─────────────────────────────────────────────────── */
  function onViewEnter() {
    ensureMonaco(() => {
      const text = buildIBISText(readFormValues());
      if (_editor && !_editor.getValue()) {
        _editor.setValue(text);
      }
    });

    // Wire form inputs (in case this is first entry)
    document.querySelectorAll('.gen-form [data-field]').forEach(el => {
      el.removeEventListener('input', updateEditorFromForm);
      el.addEventListener('input', updateEditorFromForm);
    });

    // Generate button
    const genBtn = document.getElementById('btn-generate-ibis');
    if (genBtn && !genBtn._wired) {
      genBtn.addEventListener('click', updateEditorFromForm);
      genBtn._wired = true;
    }

    // Export button
    const expBtn = document.getElementById('btn-export-ibis');
    if (expBtn && !expBtn._wired) {
      expBtn.addEventListener('click', exportCurrent);
      expBtn._wired = true;
    }
  }

  return { onViewEnter, exportCurrent, loadForEditing, buildIBISText };
})();
