"""
report_generator.py — PDF and Word report generation for IBIS analysis.
"""
from __future__ import annotations
import io
from datetime import datetime
from typing import Optional

import sys, os
_BACKEND = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _BACKEND not in sys.path:
    sys.path.insert(0, _BACKEND)
from models.schemas import ParsedIBIS
from validator.ibis_validator import validate


def generate_pdf(parsed: ParsedIBIS) -> bytes:
    """Generate a PDF analysis report using ReportLab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer, HRFlowable
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    RE_PURPLE = colors.HexColor('#6366f1')
    RE_DARK   = colors.HexColor('#1a1a2e')
    RE_GRAY   = colors.HexColor('#666680')

    title_style = ParagraphStyle('Title', parent=styles['Title'],
                                 textColor=RE_PURPLE, fontSize=20, spaceAfter=6)
    h2_style = ParagraphStyle('H2', parent=styles['Heading2'],
                              textColor=RE_DARK, fontSize=13, spaceBefore=12, spaceAfter=4)
    body_style = ParagraphStyle('Body', parent=styles['Normal'],
                                fontSize=9, textColor=RE_DARK, spaceAfter=4)
    caption_style = ParagraphStyle('Caption', parent=styles['Normal'],
                                   fontSize=8, textColor=RE_GRAY, spaceAfter=8)

    validation = validate(parsed)
    comp = parsed.components[0] if parsed.components else None
    models = comp.models if comp else []

    story = []

    # Header
    story.append(Paragraph('IBIS Analysis Report', title_style))
    story.append(Paragraph(f'Generated by IBIS-Studio — Rising Edge &nbsp;|&nbsp; {datetime.now().strftime("%Y-%m-%d %H:%M")}', caption_style))
    story.append(HRFlowable(width='100%', color=RE_PURPLE, thickness=2, spaceAfter=12))

    # Summary table
    story.append(Paragraph('File Summary', h2_style))
    summary_data = [
        ['Parameter', 'Value'],
        ['Component', comp.name if comp else '—'],
        ['Manufacturer', comp.manufacturer if comp else parsed.manufacturer or '—'],
        ['IBIS Version', parsed.version or '—'],
        ['File Name', parsed.file_name or '—'],
        ['Date', parsed.date or '—'],
        ['Total Pins', str(len(comp.pins)) if comp else '0'],
        ['Total Models', str(len(models))],
        ['Has Waveforms', 'Yes' if any(m.rising_waveforms or m.falling_waveforms for m in models) else 'No'],
        ['Has Ramp Data', 'Yes' if any(m.ramp and (m.ramp.dvdt_r or m.ramp.dvdt_f) for m in models) else 'No'],
    ]
    t = Table(summary_data, colWidths=[6*cm, 10*cm])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), RE_PURPLE),
        ('TEXTCOLOR',  (0, 0), (-1, 0), colors.white),
        ('FONTSIZE',   (0, 0), (-1, 0), 9),
        ('FONTSIZE',   (0, 1), (-1, -1), 9),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#f8f8ff'), colors.white]),
        ('GRID',       (0, 0), (-1, -1), 0.5, colors.HexColor('#ddddee')),
        ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.3*cm))

    # Scores
    story.append(Paragraph('Validation Scores', h2_style))
    score_data = [
        ['Metric', 'Score'],
        ['Overall',          f'{validation.overall_score}/100'],
        ['Syntax',           f'{validation.syntax_score}/100'],
        ['Simulation Ready', f'{validation.sim_score}/100'],
        ['Quality',          f'{validation.quality_score}/100'],
    ]
    ts = Table(score_data, colWidths=[8*cm, 8*cm])
    ts.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), RE_PURPLE),
        ('TEXTCOLOR',  (0, 0), (-1, 0), colors.white),
        ('FONTSIZE',   (0, 0), (-1, -1), 9),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#f8f8ff'), colors.white]),
        ('GRID',       (0, 0), (-1, -1), 0.5, colors.HexColor('#ddddee')),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(ts)
    story.append(Spacer(1, 0.3*cm))

    # Validation issues
    errors   = [i for i in validation.issues if i.severity == 'error']
    warnings = [i for i in validation.issues if i.severity == 'warn']

    if errors or warnings:
        story.append(Paragraph('Issues Found', h2_style))
        for issue in errors + warnings:
            icon = '✗' if issue.severity == 'error' else '⚠'
            story.append(Paragraph(
                f'<b>[{issue.rule_id}]</b> {icon} {issue.name}: {issue.message}',
                body_style
            ))

    # Model list
    if models:
        story.append(Paragraph('Models', h2_style))
        model_data = [['Name', 'Type', 'Voltage (typ)', 'Pullup pts', 'Pulldown pts', 'Waveforms']]
        for m in models:
            vtyp = f'{m.voltage_range.typ:.1f}V' if m.voltage_range and m.voltage_range.typ else '—'
            wf = len(m.rising_waveforms) + len(m.falling_waveforms)
            model_data.append([
                m.name, m.model_type or '—', vtyp,
                str(len(m.pullup)), str(len(m.pulldown)), str(wf),
            ])
        tm = Table(model_data, colWidths=[4.5*cm, 3*cm, 3*cm, 2*cm, 2.5*cm, 2.5*cm])
        tm.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), RE_PURPLE),
            ('TEXTCOLOR',  (0, 0), (-1, 0), colors.white),
            ('FONTSIZE',   (0, 0), (-1, -1), 8),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#f8f8ff'), colors.white]),
            ('GRID',       (0, 0), (-1, -1), 0.5, colors.HexColor('#ddddee')),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(tm)

    # Footer
    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width='100%', color=RE_GRAY, thickness=0.5))
    story.append(Paragraph(
        f'IBIS-Studio — Rising Edge &nbsp;|&nbsp; {datetime.now().year}',
        caption_style,
    ))

    doc.build(story)
    return buf.getvalue()


def generate_docx(parsed: ParsedIBIS) -> bytes:
    """Generate a Word document analysis report using python-docx."""
    from docx import Document
    from docx.shared import Pt, RGBColor, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    validation = validate(parsed)
    comp = parsed.components[0] if parsed.components else None
    models = comp.models if comp else []

    doc = Document()

    # Styles
    RE_PURPLE = RGBColor(0x63, 0x66, 0xF1)

    # Title
    t = doc.add_heading('IBIS Analysis Report', 0)
    t.runs[0].font.color.rgb = RE_PURPLE

    doc.add_paragraph(
        f'Generated by IBIS-Studio — Rising Edge | {datetime.now().strftime("%Y-%m-%d %H:%M")}'
    ).runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x99)

    # Summary
    doc.add_heading('File Summary', 1)
    tbl = doc.add_table(rows=1, cols=2)
    tbl.style = 'Table Grid'
    hdr = tbl.rows[0].cells
    hdr[0].text = 'Parameter'
    hdr[1].text = 'Value'

    rows = [
        ('Component', comp.name if comp else '—'),
        ('Manufacturer', comp.manufacturer if comp else parsed.manufacturer or '—'),
        ('IBIS Version', parsed.version or '—'),
        ('File Name', parsed.file_name or '—'),
        ('Total Pins', str(len(comp.pins)) if comp else '0'),
        ('Total Models', str(len(models))),
        ('Has Waveforms', 'Yes' if any(m.rising_waveforms or m.falling_waveforms for m in models) else 'No'),
        ('Quality Score', f'{validation.quality_score}/100'),
    ]
    for label, value in rows:
        row = tbl.add_row().cells
        row[0].text = label
        row[1].text = value

    # Scores
    doc.add_heading('Validation Scores', 1)
    for label, val in [
        ('Overall', validation.overall_score),
        ('Syntax', validation.syntax_score),
        ('Simulation Ready', validation.sim_score),
        ('Quality', validation.quality_score),
    ]:
        doc.add_paragraph(f'{label}: {val}/100', style='List Bullet')

    # Issues
    errors = [i for i in validation.issues if i.severity == 'error']
    warnings = [i for i in validation.issues if i.severity == 'warn']
    if errors or warnings:
        doc.add_heading('Issues Found', 1)
        for issue in errors + warnings:
            p = doc.add_paragraph(style='List Bullet')
            p.add_run(f'[{issue.rule_id}] ').bold = True
            p.add_run(f'{issue.name}: {issue.message}')

    # Footer
    doc.add_paragraph()
    p = doc.add_paragraph(f'IBIS-Studio — Rising Edge © {datetime.now().year}')
    p.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x99)
    p.runs[0].font.size = Pt(8)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
